name: Build Release Binaries

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  # Building using the github runner environement directly.
  make:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets: [
          [mips32],
          [mips32el],
          [mips64],
          [mips64el]
        ]
      fail-fast: false
    env:
      TARGET: ${{ matrix.targets[0] }}
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc zlib1g-dev libcurl4-openssl-dev libcjson-dev
    - name: Build (Static)
      run: |
        wget -q https://archive.openwrt.org/releases/25.12.0/targets/ramips/mt7621/openwrt-sdk-25.12.0-ramips-mt7621_gcc-14.3.0_musl.Linux-x86_64.tar.zst
        tar -xf openwrt-*.tar.zst
        cd openwrt-sdk-25.12.0-ramips-mt7621_gcc-14.3.0_musl.Linux-x86_64
        export TOOLCHAIN=$(pwd)/staging_dir/toolchain-mipsel_24kc_gcc-14.3.0_musl/bin
        export STAGING_DIR=$(pwd)/staging_dir
        export PATH=$TOOLCHAIN:$PATH
        ./scripts/feeds update -a
        ./scripts/feeds install libcurl
        find -name curl.h
        cd ..
        git clone https://github.com/DaveGamble/cJSON.git
        mv cJSON cjson
        cd cjson && make CC=mipsel-openwrt-linux-gcc && cd ..
        git clone https://github.com/curl/curl.git
        make CC=mipsel-openwrt-linux-gcc LDFLAGS="-static -lcurl cjson/libcjson.a" CFLAGS="-I. -Icurl/include"
        ./nbtv --version 
    - uses: actions/upload-artifact@v4
      with:
        name: linux-x64-${{ matrix.targets[0] }}
        path: nbtv
