name: Build Release Binaries

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  # Building using the github runner environement directly.
  make:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets: [
          [mips32],
          [mips32el],
          [mips64],
          [mips64el]
        ]
      fail-fast: false
    env:
      TARGET: ${{ matrix.targets[0] }}
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc zlib1g-dev libcurl4-openssl-dev libcjson-dev
    - name: Build (Static)
      run: |
        sudo apt-get install -y gcc libcurl4-openssl-dev
        wget https://archive.openwrt.org/chaos_calmer/15.05.1/ramips/mt7621/OpenWrt-SDK-15.05.1-ramips-mt7621_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2
        tar -xjvf OpenWrt-SDK-*.tar.bz2
        mv OpenWrt-SDK-* openwrt-sdk
        export TOOLCHAIN=$(pwd)/openwrt-sdk/staging_dir/toolchain-mipsel_24kc_gcc-4.8-linaro_uClibc-0.9.33.2/bin
        export PATH=$TOOLCHAIN:$PATH
        git clone https://github.com/DaveGamble/cJSON.git
        cd cJSON && make CC=mipsel-openwrt-linux-gcc && cd ..
        git clone https://github.com/curl/curl.git
        cd curl && autoreconf -fi
        ./configure --disable-shared --enable-static --without-ssl --without-libpsl --without-librtmp --without-zstd --without-brotli
        make CC=mipsel-openwrt-linux-gcc -j$(nproc) && cd ..
        make CC=mipsel-openwrt-linux-gcc LDFLAGS="-static curl/lib/.libs/libcurl.a cJSON/libcjson.a -lz" CFLAGS="-IcJSON -Icurl/include-static"
        ./nbtv --version 
    - uses: actions/upload-artifact@v4
      with:
        name: linux-x64-${{ matrix.targets[0] }}
        path: nbtv
